### ISSUE TITLE
Is it possible for me to ask you some questions encountered during my studying process?

### ISSUE THREAD

**Issue by silence-debug-hue** [mitre-rise/coupled-networks#1]
As you can see, in the file "**couplednetworks.py**" 
There is a line of codes:  **select_each_replicate = config['select_each_replicate']**
but when I started to run the python program, it indicated me that there was a missing part in the **config.json**----  since no "**select_each_replicate**" part  lies in the corresponding file
excerpted from Python-spyder [KeyError: 'select_each_replicate']
Am I wrong understanding this part or if I am missing something else that is important?

**Comment by veneman** [comment]
I see that select_each_replicate was not in the example config.json file and that's why you ran into that issue. I added ```"select_each_replicate":false,``` to that file. ```select_each_replicate``` should be false unless you're doing a topological-only run like with the config_p_sweep_topological.json config.

**Comment by silence-debug-hue** [comment]
Is that correct that there is no **comm_status_filename** or **grid_status_filename**
in the provided files?
