### ISSUE TITLE
Sorry to disturb, but sincerely ask the last question!

### ISSUE THREAD

**Issue by silence-debug-hue** [mitre-rise/coupled-networks#2]
Professor,
    Could U tell me what is the **grid status files** mean? That is, is it correct that there is no this kind file in the provides documents? 
   Since the **comm_status_filename** and **grid_status_filename**  will be generated by the initial number **str(mpid)** from 1 to xxx, I am really confused. At least, people should be confirmed that in what kind of form and structure is the data utilized and  inputed.
   I saw u professor closed this issue six days ago, if there exists any inconvenience, could u please contact me with my email address :774353404@qq.com. Many thanks from a student and wish u all the best in the future research!

**Comment by veneman** [comment]
The status files are used for the Python and MATLAB parts of the program to communicate with each other. If you're using Windows you'd need to change the following in ```couplednetworks.py```:

```
comm_status_filename = '/tmp/comm_status_' + str(mpid) + '.csv'
grid_status_filename = '/tmp/grid_status_' + str(mpid) + '.csv'
```

To something like:

```
comm_status_filename = 'C:\Users\<username>\AppData\Local\Temp\comm_status_' + str(mpid) + '.csv'
grid_status_filename = 'C:\Users\<username>\AppData\Local\Temp\grid_status_' + str(mpid) + '.csv'
```

The file format and interactions between them are in this diagram which is linked in the README:
https://github.com/mitre-rise/coupled-networks/blob/master/images/coupling-model-architecture.png

**Comment by silence-debug-hue** [comment]
Thanks a lot!
